import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

/**
 * Initialize the Gemini AI client with the public API key.
 * This client is used for all AI-related tasks in the frontend.
 */
const ai = new GoogleGenAI({ 
  apiKey: process.env.NEXT_PUBLIC_GEMINI_API_KEY || '' 
});

/**
 * Removes and replaces the background of an image using Gemini 2.5 Flash Image.
 * 
 * @param originalImageBase64 - The base64 encoded string of the original image.
 * @param mimeType - The IANA standard MIME type of the original image (e.g., 'image/png').
 * @param backgroundSpec - Either a text prompt or a base64 encoded background image.
 * @returns A promise that resolves to the new image Data URI.
 */
export async function processBackgroundRemoval(
  originalImageBase64: string,
  mimeType: string,
  backgroundSpec: { prompt?: string; backgroundImageBase64?: string; backgroundMimeType?: string }
): Promise<string> {
  // Extract the raw base64 data (remove the data:image/...;base64, prefix if present)
  const cleanOriginal = originalImageBase64.replace(/^data:image\/\w+;base64,/, '');

  const parts: any[] = [
    {
      inlineData: {
        data: cleanOriginal,
        mimeType: mimeType,
      },
    },
  ];

  if (backgroundSpec.backgroundImageBase64 && backgroundSpec.backgroundMimeType) {
    const cleanBackground = backgroundSpec.backgroundImageBase64.replace(/^data:image\/\w+;base64,/, '');
    parts.push({
      inlineData: {
        data: cleanBackground,
        mimeType: backgroundSpec.backgroundMimeType,
      },
    });
    parts.push({
      text: "Remove the background from the first image and replace it with the second image. Ensure the subject from the first image is perfectly integrated into the new background.",
    });
  } else if (backgroundSpec.prompt) {
    parts.push({
      text: `Remove the background from this image and replace it with a new background based on this prompt: "${backgroundSpec.prompt}". Ensure the subject is perfectly integrated and the lighting matches the new background.`,
    });
  } else {
    parts.push({
      text: "Remove the background from this image and make it transparent or a clean white background.",
    });
  }

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: parts,
      },
      config: {
        systemInstruction: "You are an expert image editor. Your task is to remove the background from the provided image and replace it as requested. You must output the result as an image part. Do not provide any text explanation.",
        maxOutputTokens: 8192,
      },
    });

    // Debug logging for safety blocks
    if (response.candidates?.[0]?.finishReason === 'SAFETY') {
      console.error("Gemini AI blocked the request due to safety filters:", response.candidates[0].safetyRatings);
      throw new Error("The AI model blocked the request due to safety filters. Please try with a different image.");
    }

    // Debug logging for text output
    if (response.text) {
      console.log("Gemini AI Response Text:", response.text);
    }

    // Iterate through all parts to find the generated image
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const base64EncodeString: string = part.inlineData.data;
        return `data:image/png;base64,${base64EncodeString}`;
      }
    }

    // If we have text but no image, maybe the model is refusing or just talking
    if (response.text) {
      throw new Error(`AI returned text instead of an image: ${response.text}`);
    }

    throw new Error("No image was generated by the AI model. The model might have failed to process the request or returned an empty response.");
  } catch (error) {
    console.error("Gemini AI Background Removal Error:", error);
    throw error;
  }
}

/**
 * Removes watermarks from an image using Gemini 3.1 Flash Image.
 * 
 * @param originalImageBase64 - The base64 encoded string of the original image.
 * @param maskBase64 - The base64 encoded string of the mask (white on black).
 * @returns A promise that resolves to the cleaned image Data URI.
 */
export async function processWatermarkRemoval(
  originalImageBase64: string,
  maskBase64: string
): Promise<string> {
  // Extract the raw base64 data
  const cleanOriginal = originalImageBase64.replace(/^data:image\/\w+;base64,/, '');
  const cleanMask = maskBase64.replace(/^data:image\/\w+;base64,/, '');

  const parts: any[] = [
    {
      inlineData: {
        data: cleanOriginal,
        mimeType: 'image/png',
      },
    },
    {
      inlineData: {
        data: cleanMask,
        mimeType: 'image/png',
      },
    },
    {
      text: "The first image is the original image with a watermark. The second image is a mask where the white areas indicate the location of the watermark. Please remove the watermark from the original image by intelligently filling in the masked areas based on the surrounding context. Ensure the restoration is seamless and matches the texture and lighting of the original image. Output only the cleaned image.",
    },
  ];

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: parts,
      },
      config: {
        systemInstruction: "You are an expert image restoration specialist. Your task is to remove watermarks or unwanted objects from images based on a provided mask. You MUST output the result as an image part. DO NOT provide any text explanation or conversation. ONLY THE IMAGE.",
        maxOutputTokens: 8192,
      },
    });

    // Debug logging for safety blocks
    if (response.candidates?.[0]?.finishReason === 'SAFETY') {
      console.error("Gemini AI blocked the request due to safety filters:", response.candidates[0].safetyRatings);
      throw new Error("The AI model blocked the request due to safety filters. Please try with a different image.");
    }

    // Debug logging for text output
    if (response.text) {
      console.log("Gemini AI Response Text:", response.text);
    }

    // Iterate through all parts to find the generated image
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const base64EncodeString: string = part.inlineData.data;
        return `data:image/png;base64,${base64EncodeString}`;
      }
    }

    // If we have text but no image, maybe the model is refusing or just talking
    if (response.text) {
      throw new Error(`AI returned text instead of an image: ${response.text}`);
    }

    throw new Error("No image was generated by the AI model. The model might have failed to process the request or returned an empty response.");
  } catch (error) {
    console.error("Gemini AI Watermark Removal Error:", error);
    throw error;
  }
}

/**
 * Extracts text or generates a caption from an image using Gemini 3 Flash.
 * 
 * @param imageBase64 - The base64 encoded string of the image.
 * @param mimeType - The IANA standard MIME type of the image.
 * @param mode - 'extract' for OCR, 'caption' for descriptive text.
 * @returns A promise that resolves to the extracted text or caption.
 */
export async function processImageToText(
  imageBase64: string,
  mimeType: string,
  mode: 'extract' | 'caption' = 'extract'
): Promise<string> {
  const cleanImage = imageBase64.replace(/^data:image\/\w+;base64,/, '');

  const prompt = mode === 'extract' 
    ? "Please extract all the text visible in this image. Maintain the original formatting and layout as much as possible. If there is no text, please state so."
    : "Please provide a detailed and descriptive caption for this image. Describe the main subjects, the setting, colors, and any notable actions or emotions conveyed.";

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanImage,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        systemInstruction: "You are an expert at visual analysis and OCR. Your task is to accurately describe or extract text from images as requested. Provide clean, well-formatted text output.",
      },
    });

    if (response.candidates?.[0]?.finishReason === 'SAFETY') {
      throw new Error("The AI model blocked the request due to safety filters. Please try with a different image.");
    }

    const text = response.text;
    if (!text) {
      throw new Error("The AI model failed to generate any text for this image.");
    }

    return text;
  } catch (error) {
    console.error("Gemini AI Image-to-Text Error:", error);
    throw error;
  }
}
